package docs

import _ "embed"

//go:embed api/openapi.yaml
var OpenAPI string

// ConfigSchema is the generated JSON schema for blocky's configuration file.
// It is regenerated by tools/schemagen via `go generate ./config/...`.
//
//go:embed config.schema.json
var ConfigSchema []byte
