linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - revive
    - stylecheck
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - gofmt
    - goimports
    - depguard
    - misspell
    - lll
    - unparam
    - dogsled
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godox
    - nakedret
    - prealloc
    - whitespace
    - wsl
    - exportloopref
  disable:
    - noctx
    - scopelint

  disable-all: false
  presets:
    - bugs
    - unused
  fast: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - dupl
