site_name: blocky
site_description: blocky Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

        # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0xERR0R/blocky
    - icon: simple/codeberg
      link: https://codeberg.org/0xERR0R/blocky
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/spx01/blocky
repo_url: https://github.com/0xERR0R/blocky
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - pymdownx.snippets:
      base_path: [docs]
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - "Welcome": "index.md"
  - "Configuration": "configuration.md"
  - "Installation": "installation.md"
  - "Prometheus / Grafana": "prometheus_grafana.md"
  - "Interfaces": "interfaces.md"
  - "Network configuration": "network_configuration.md"
  - "Additional information": "additional_information.md"
