site_name: blocky
site_description: blocky Documentation
theme:
  name: material
  palette:
    primary: teal
    accent: teal
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0xERR0R/blocky
    - icon: simple/codeberg
      link: https://codeberg.org/0xERR0R/blocky
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/spx01/blocky
repo_url: https://github.com/0xERR0R/blocky

markdown_extensions:
  - abbr
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - 'Welcome': 'index.md'
  - 'Configuration': 'configuration.md'
  - 'Installation': 'installation.md'
  - 'Prometheus / Grafana': 'prometheus_grafana.md'
  - 'Interfaces': 'interfaces.md'
  - 'Network configuration': 'network_configuration.md'
  - 'Additional information': 'additional_information.md'
