// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package log

import (
	"fmt"
	"strings"
)

const (
	// FormatTypeText is a FormatType of type Text.
	// Human-readable text.
	FormatTypeText FormatType = iota
	// FormatTypeJson is a FormatType of type Json.
	// Structured JSON.
	FormatTypeJson
)

var ErrInvalidFormatType = fmt.Errorf("not a valid FormatType, try [%s]", strings.Join(_FormatTypeNames, ", "))

const _FormatTypeName = "textjson"

var _FormatTypeNames = []string{
	_FormatTypeName[0:4],
	_FormatTypeName[4:8],
}

// FormatTypeNames returns a list of possible string values of FormatType.
func FormatTypeNames() []string {
	tmp := make([]string, len(_FormatTypeNames))
	copy(tmp, _FormatTypeNames)
	return tmp
}

var _FormatTypeMap = map[FormatType]string{
	FormatTypeText: _FormatTypeName[0:4],
	FormatTypeJson: _FormatTypeName[4:8],
}

// String implements the Stringer interface.
func (x FormatType) String() string {
	if str, ok := _FormatTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("FormatType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FormatType) IsValid() bool {
	_, ok := _FormatTypeMap[x]
	return ok
}

var _FormatTypeValue = map[string]FormatType{
	_FormatTypeName[0:4]: FormatTypeText,
	_FormatTypeName[4:8]: FormatTypeJson,
}

// ParseFormatType attempts to convert a string to a FormatType.
func ParseFormatType(name string) (FormatType, error) {
	if x, ok := _FormatTypeValue[name]; ok {
		return x, nil
	}
	return FormatType(0), fmt.Errorf("%s is %w", name, ErrInvalidFormatType)
}

// MarshalText implements the text marshaller method.
func (x FormatType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FormatType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseFormatType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *FormatType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

// EnumDescriptions returns each enum value's description, taken from the
// `// comment` in the ENUM(...) declaration. Generated; do not edit.
func (FormatType) EnumDescriptions() map[string]string {
	return map[string]string{
		"text": "Human-readable text.",
		"json": "Structured JSON.",
	}
}

// EnumValues returns the enum's accepted string values, used to build the JSON
// schema enum constraint. Generated; do not edit.
func (FormatType) EnumValues() []string {
	return FormatTypeNames()
}

const (
	// TargetTypeStdout is a TargetType of type Stdout.
	// Standard output.
	TargetTypeStdout TargetType = iota
	// TargetTypeStderr is a TargetType of type Stderr.
	// Standard error.
	TargetTypeStderr
	// TargetTypeSyslog is a TargetType of type Syslog.
	// System log, each entry at the priority matching its level.
	TargetTypeSyslog
)

var ErrInvalidTargetType = fmt.Errorf("not a valid TargetType, try [%s]", strings.Join(_TargetTypeNames, ", "))

const _TargetTypeName = "stdoutstderrsyslog"

var _TargetTypeNames = []string{
	_TargetTypeName[0:6],
	_TargetTypeName[6:12],
	_TargetTypeName[12:18],
}

// TargetTypeNames returns a list of possible string values of TargetType.
func TargetTypeNames() []string {
	tmp := make([]string, len(_TargetTypeNames))
	copy(tmp, _TargetTypeNames)
	return tmp
}

var _TargetTypeMap = map[TargetType]string{
	TargetTypeStdout: _TargetTypeName[0:6],
	TargetTypeStderr: _TargetTypeName[6:12],
	TargetTypeSyslog: _TargetTypeName[12:18],
}

// String implements the Stringer interface.
func (x TargetType) String() string {
	if str, ok := _TargetTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("TargetType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TargetType) IsValid() bool {
	_, ok := _TargetTypeMap[x]
	return ok
}

var _TargetTypeValue = map[string]TargetType{
	_TargetTypeName[0:6]:   TargetTypeStdout,
	_TargetTypeName[6:12]:  TargetTypeStderr,
	_TargetTypeName[12:18]: TargetTypeSyslog,
}

// ParseTargetType attempts to convert a string to a TargetType.
func ParseTargetType(name string) (TargetType, error) {
	if x, ok := _TargetTypeValue[name]; ok {
		return x, nil
	}
	return TargetType(0), fmt.Errorf("%s is %w", name, ErrInvalidTargetType)
}

// MarshalText implements the text marshaller method.
func (x TargetType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TargetType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseTargetType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *TargetType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

// EnumDescriptions returns each enum value's description, taken from the
// `// comment` in the ENUM(...) declaration. Generated; do not edit.
func (TargetType) EnumDescriptions() map[string]string {
	return map[string]string{
		"stdout": "Standard output.",
		"stderr": "Standard error.",
		"syslog": "System log, each entry at the priority matching its level.",
	}
}

// EnumValues returns the enum's accepted string values, used to build the JSON
// schema enum constraint. Generated; do not edit.
func (TargetType) EnumValues() []string {
	return TargetTypeNames()
}
