// Package configapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package configapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Apply pending configuration changes
	// (POST /apply)
	ApplyConfig(w http.ResponseWriter, r *http.Request)
	// Get block settings
	// (GET /block-settings)
	GetBlockSettings(w http.ResponseWriter, r *http.Request)
	// Update block settings
	// (PUT /block-settings)
	PutBlockSettings(w http.ResponseWriter, r *http.Request)
	// List blocklist sources
	// (GET /blocklist-sources)
	ListBlocklistSources(w http.ResponseWriter, r *http.Request, params ListBlocklistSourcesParams)
	// Create a blocklist source
	// (POST /blocklist-sources)
	CreateBlocklistSource(w http.ResponseWriter, r *http.Request)
	// Delete a blocklist source
	// (DELETE /blocklist-sources/{id})
	DeleteBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID)
	// Get a blocklist source by ID
	// (GET /blocklist-sources/{id})
	GetBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID)
	// Update a blocklist source
	// (PUT /blocklist-sources/{id})
	UpdateBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID)
	// List all client groups
	// (GET /client-groups)
	ListClientGroups(w http.ResponseWriter, r *http.Request)
	// Delete a client group
	// (DELETE /client-groups/{name})
	DeleteClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName)
	// Get a client group by name
	// (GET /client-groups/{name})
	GetClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName)
	// Create or update a client group
	// (PUT /client-groups/{name})
	PutClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName)
	// List custom DNS entries
	// (GET /custom-dns)
	ListCustomDNSEntries(w http.ResponseWriter, r *http.Request)
	// Create a custom DNS entry
	// (POST /custom-dns)
	CreateCustomDNSEntry(w http.ResponseWriter, r *http.Request)
	// Delete a custom DNS entry
	// (DELETE /custom-dns/{id})
	DeleteCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID)
	// Get a custom DNS entry by ID
	// (GET /custom-dns/{id})
	GetCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID)
	// Update a custom DNS entry
	// (PUT /custom-dns/{id})
	UpdateCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Apply pending configuration changes
// (POST /apply)
func (_ Unimplemented) ApplyConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get block settings
// (GET /block-settings)
func (_ Unimplemented) GetBlockSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update block settings
// (PUT /block-settings)
func (_ Unimplemented) PutBlockSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List blocklist sources
// (GET /blocklist-sources)
func (_ Unimplemented) ListBlocklistSources(w http.ResponseWriter, r *http.Request, params ListBlocklistSourcesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a blocklist source
// (POST /blocklist-sources)
func (_ Unimplemented) CreateBlocklistSource(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a blocklist source
// (DELETE /blocklist-sources/{id})
func (_ Unimplemented) DeleteBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a blocklist source by ID
// (GET /blocklist-sources/{id})
func (_ Unimplemented) GetBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a blocklist source
// (PUT /blocklist-sources/{id})
func (_ Unimplemented) UpdateBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all client groups
// (GET /client-groups)
func (_ Unimplemented) ListClientGroups(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a client group
// (DELETE /client-groups/{name})
func (_ Unimplemented) DeleteClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a client group by name
// (GET /client-groups/{name})
func (_ Unimplemented) GetClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update a client group
// (PUT /client-groups/{name})
func (_ Unimplemented) PutClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List custom DNS entries
// (GET /custom-dns)
func (_ Unimplemented) ListCustomDNSEntries(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a custom DNS entry
// (POST /custom-dns)
func (_ Unimplemented) CreateCustomDNSEntry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a custom DNS entry
// (DELETE /custom-dns/{id})
func (_ Unimplemented) DeleteCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a custom DNS entry by ID
// (GET /custom-dns/{id})
func (_ Unimplemented) GetCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a custom DNS entry
// (PUT /custom-dns/{id})
func (_ Unimplemented) UpdateCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApplyConfig operation middleware
func (siw *ServerInterfaceWrapper) ApplyConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBlockSettings operation middleware
func (siw *ServerInterfaceWrapper) GetBlockSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBlockSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutBlockSettings operation middleware
func (siw *ServerInterfaceWrapper) PutBlockSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutBlockSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBlocklistSources operation middleware
func (siw *ServerInterfaceWrapper) ListBlocklistSources(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBlocklistSourcesParams

	// ------------- Optional query parameter "group_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_name", r.URL.Query(), &params.GroupName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_name", Err: err})
		return
	}

	// ------------- Optional query parameter "list_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "list_type", r.URL.Query(), &params.ListType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBlocklistSources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBlocklistSource operation middleware
func (siw *ServerInterfaceWrapper) CreateBlocklistSource(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBlocklistSource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteBlocklistSource operation middleware
func (siw *ServerInterfaceWrapper) DeleteBlocklistSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ResourceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteBlocklistSource(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBlocklistSource operation middleware
func (siw *ServerInterfaceWrapper) GetBlocklistSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ResourceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBlocklistSource(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBlocklistSource operation middleware
func (siw *ServerInterfaceWrapper) UpdateBlocklistSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ResourceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBlocklistSource(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClientGroups operation middleware
func (siw *ServerInterfaceWrapper) ListClientGroups(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClientGroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteClientGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteClientGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name ClientGroupName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteClientGroup(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClientGroup operation middleware
func (siw *ServerInterfaceWrapper) GetClientGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name ClientGroupName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClientGroup(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutClientGroup operation middleware
func (siw *ServerInterfaceWrapper) PutClientGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name ClientGroupName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutClientGroup(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCustomDNSEntries operation middleware
func (siw *ServerInterfaceWrapper) ListCustomDNSEntries(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCustomDNSEntries(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCustomDNSEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomDNSEntry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCustomDNSEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCustomDNSEntry operation middleware
func (siw *ServerInterfaceWrapper) DeleteCustomDNSEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ResourceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCustomDNSEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomDNSEntry operation middleware
func (siw *ServerInterfaceWrapper) GetCustomDNSEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ResourceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomDNSEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCustomDNSEntry operation middleware
func (siw *ServerInterfaceWrapper) UpdateCustomDNSEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ResourceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCustomDNSEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/apply", wrapper.ApplyConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/block-settings", wrapper.GetBlockSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/block-settings", wrapper.PutBlockSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/blocklist-sources", wrapper.ListBlocklistSources)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/blocklist-sources", wrapper.CreateBlocklistSource)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/blocklist-sources/{id}", wrapper.DeleteBlocklistSource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/blocklist-sources/{id}", wrapper.GetBlocklistSource)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/blocklist-sources/{id}", wrapper.UpdateBlocklistSource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/client-groups", wrapper.ListClientGroups)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/client-groups/{name}", wrapper.DeleteClientGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/client-groups/{name}", wrapper.GetClientGroup)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/client-groups/{name}", wrapper.PutClientGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/custom-dns", wrapper.ListCustomDNSEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/custom-dns", wrapper.CreateCustomDNSEntry)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/custom-dns/{id}", wrapper.DeleteCustomDNSEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/custom-dns/{id}", wrapper.GetCustomDNSEntry)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/custom-dns/{id}", wrapper.UpdateCustomDNSEntry)
	})

	return r
}

type BadRequestJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ApplyConfigRequestObject struct {
}

type ApplyConfigResponseObject interface {
	VisitApplyConfigResponse(w http.ResponseWriter) error
}

type ApplyConfig200JSONResponse ApplyResponse

func (response ApplyConfig200JSONResponse) VisitApplyConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyConfig500JSONResponse ApplyResponse

func (response ApplyConfig500JSONResponse) VisitApplyConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBlockSettingsRequestObject struct {
}

type GetBlockSettingsResponseObject interface {
	VisitGetBlockSettingsResponse(w http.ResponseWriter) error
}

type GetBlockSettings200JSONResponse BlockSettings

func (response GetBlockSettings200JSONResponse) VisitGetBlockSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutBlockSettingsRequestObject struct {
	Body *PutBlockSettingsJSONRequestBody
}

type PutBlockSettingsResponseObject interface {
	VisitPutBlockSettingsResponse(w http.ResponseWriter) error
}

type PutBlockSettings200JSONResponse BlockSettings

func (response PutBlockSettings200JSONResponse) VisitPutBlockSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutBlockSettings400JSONResponse struct{ BadRequestJSONResponse }

func (response PutBlockSettings400JSONResponse) VisitPutBlockSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListBlocklistSourcesRequestObject struct {
	Params ListBlocklistSourcesParams
}

type ListBlocklistSourcesResponseObject interface {
	VisitListBlocklistSourcesResponse(w http.ResponseWriter) error
}

type ListBlocklistSources200JSONResponse []BlocklistSource

func (response ListBlocklistSources200JSONResponse) VisitListBlocklistSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateBlocklistSourceRequestObject struct {
	Body *CreateBlocklistSourceJSONRequestBody
}

type CreateBlocklistSourceResponseObject interface {
	VisitCreateBlocklistSourceResponse(w http.ResponseWriter) error
}

type CreateBlocklistSource201JSONResponse BlocklistSource

func (response CreateBlocklistSource201JSONResponse) VisitCreateBlocklistSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateBlocklistSource400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateBlocklistSource400JSONResponse) VisitCreateBlocklistSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteBlocklistSourceRequestObject struct {
	Id ResourceID `json:"id"`
}

type DeleteBlocklistSourceResponseObject interface {
	VisitDeleteBlocklistSourceResponse(w http.ResponseWriter) error
}

type DeleteBlocklistSource204Response struct {
}

func (response DeleteBlocklistSource204Response) VisitDeleteBlocklistSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteBlocklistSource404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteBlocklistSource404JSONResponse) VisitDeleteBlocklistSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetBlocklistSourceRequestObject struct {
	Id ResourceID `json:"id"`
}

type GetBlocklistSourceResponseObject interface {
	VisitGetBlocklistSourceResponse(w http.ResponseWriter) error
}

type GetBlocklistSource200JSONResponse BlocklistSource

func (response GetBlocklistSource200JSONResponse) VisitGetBlocklistSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBlocklistSource404JSONResponse struct{ NotFoundJSONResponse }

func (response GetBlocklistSource404JSONResponse) VisitGetBlocklistSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateBlocklistSourceRequestObject struct {
	Id   ResourceID `json:"id"`
	Body *UpdateBlocklistSourceJSONRequestBody
}

type UpdateBlocklistSourceResponseObject interface {
	VisitUpdateBlocklistSourceResponse(w http.ResponseWriter) error
}

type UpdateBlocklistSource200JSONResponse BlocklistSource

func (response UpdateBlocklistSource200JSONResponse) VisitUpdateBlocklistSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateBlocklistSource400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateBlocklistSource400JSONResponse) VisitUpdateBlocklistSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateBlocklistSource404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateBlocklistSource404JSONResponse) VisitUpdateBlocklistSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListClientGroupsRequestObject struct {
}

type ListClientGroupsResponseObject interface {
	VisitListClientGroupsResponse(w http.ResponseWriter) error
}

type ListClientGroups200JSONResponse []ClientGroup

func (response ListClientGroups200JSONResponse) VisitListClientGroupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteClientGroupRequestObject struct {
	Name ClientGroupName `json:"name"`
}

type DeleteClientGroupResponseObject interface {
	VisitDeleteClientGroupResponse(w http.ResponseWriter) error
}

type DeleteClientGroup204Response struct {
}

func (response DeleteClientGroup204Response) VisitDeleteClientGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteClientGroup404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteClientGroup404JSONResponse) VisitDeleteClientGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetClientGroupRequestObject struct {
	Name ClientGroupName `json:"name"`
}

type GetClientGroupResponseObject interface {
	VisitGetClientGroupResponse(w http.ResponseWriter) error
}

type GetClientGroup200JSONResponse ClientGroup

func (response GetClientGroup200JSONResponse) VisitGetClientGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClientGroup404JSONResponse struct{ NotFoundJSONResponse }

func (response GetClientGroup404JSONResponse) VisitGetClientGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutClientGroupRequestObject struct {
	Name ClientGroupName `json:"name"`
	Body *PutClientGroupJSONRequestBody
}

type PutClientGroupResponseObject interface {
	VisitPutClientGroupResponse(w http.ResponseWriter) error
}

type PutClientGroup200JSONResponse ClientGroup

func (response PutClientGroup200JSONResponse) VisitPutClientGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutClientGroup400JSONResponse struct{ BadRequestJSONResponse }

func (response PutClientGroup400JSONResponse) VisitPutClientGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListCustomDNSEntriesRequestObject struct {
}

type ListCustomDNSEntriesResponseObject interface {
	VisitListCustomDNSEntriesResponse(w http.ResponseWriter) error
}

type ListCustomDNSEntries200JSONResponse []CustomDNSEntry

func (response ListCustomDNSEntries200JSONResponse) VisitListCustomDNSEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateCustomDNSEntryRequestObject struct {
	Body *CreateCustomDNSEntryJSONRequestBody
}

type CreateCustomDNSEntryResponseObject interface {
	VisitCreateCustomDNSEntryResponse(w http.ResponseWriter) error
}

type CreateCustomDNSEntry201JSONResponse CustomDNSEntry

func (response CreateCustomDNSEntry201JSONResponse) VisitCreateCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateCustomDNSEntry400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateCustomDNSEntry400JSONResponse) VisitCreateCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCustomDNSEntryRequestObject struct {
	Id ResourceID `json:"id"`
}

type DeleteCustomDNSEntryResponseObject interface {
	VisitDeleteCustomDNSEntryResponse(w http.ResponseWriter) error
}

type DeleteCustomDNSEntry204Response struct {
}

func (response DeleteCustomDNSEntry204Response) VisitDeleteCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCustomDNSEntry404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteCustomDNSEntry404JSONResponse) VisitDeleteCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCustomDNSEntryRequestObject struct {
	Id ResourceID `json:"id"`
}

type GetCustomDNSEntryResponseObject interface {
	VisitGetCustomDNSEntryResponse(w http.ResponseWriter) error
}

type GetCustomDNSEntry200JSONResponse CustomDNSEntry

func (response GetCustomDNSEntry200JSONResponse) VisitGetCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCustomDNSEntry404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCustomDNSEntry404JSONResponse) VisitGetCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCustomDNSEntryRequestObject struct {
	Id   ResourceID `json:"id"`
	Body *UpdateCustomDNSEntryJSONRequestBody
}

type UpdateCustomDNSEntryResponseObject interface {
	VisitUpdateCustomDNSEntryResponse(w http.ResponseWriter) error
}

type UpdateCustomDNSEntry200JSONResponse CustomDNSEntry

func (response UpdateCustomDNSEntry200JSONResponse) VisitUpdateCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCustomDNSEntry400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateCustomDNSEntry400JSONResponse) VisitUpdateCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCustomDNSEntry404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateCustomDNSEntry404JSONResponse) VisitUpdateCustomDNSEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Apply pending configuration changes
	// (POST /apply)
	ApplyConfig(ctx context.Context, request ApplyConfigRequestObject) (ApplyConfigResponseObject, error)
	// Get block settings
	// (GET /block-settings)
	GetBlockSettings(ctx context.Context, request GetBlockSettingsRequestObject) (GetBlockSettingsResponseObject, error)
	// Update block settings
	// (PUT /block-settings)
	PutBlockSettings(ctx context.Context, request PutBlockSettingsRequestObject) (PutBlockSettingsResponseObject, error)
	// List blocklist sources
	// (GET /blocklist-sources)
	ListBlocklistSources(ctx context.Context, request ListBlocklistSourcesRequestObject) (ListBlocklistSourcesResponseObject, error)
	// Create a blocklist source
	// (POST /blocklist-sources)
	CreateBlocklistSource(ctx context.Context, request CreateBlocklistSourceRequestObject) (CreateBlocklistSourceResponseObject, error)
	// Delete a blocklist source
	// (DELETE /blocklist-sources/{id})
	DeleteBlocklistSource(ctx context.Context, request DeleteBlocklistSourceRequestObject) (DeleteBlocklistSourceResponseObject, error)
	// Get a blocklist source by ID
	// (GET /blocklist-sources/{id})
	GetBlocklistSource(ctx context.Context, request GetBlocklistSourceRequestObject) (GetBlocklistSourceResponseObject, error)
	// Update a blocklist source
	// (PUT /blocklist-sources/{id})
	UpdateBlocklistSource(ctx context.Context, request UpdateBlocklistSourceRequestObject) (UpdateBlocklistSourceResponseObject, error)
	// List all client groups
	// (GET /client-groups)
	ListClientGroups(ctx context.Context, request ListClientGroupsRequestObject) (ListClientGroupsResponseObject, error)
	// Delete a client group
	// (DELETE /client-groups/{name})
	DeleteClientGroup(ctx context.Context, request DeleteClientGroupRequestObject) (DeleteClientGroupResponseObject, error)
	// Get a client group by name
	// (GET /client-groups/{name})
	GetClientGroup(ctx context.Context, request GetClientGroupRequestObject) (GetClientGroupResponseObject, error)
	// Create or update a client group
	// (PUT /client-groups/{name})
	PutClientGroup(ctx context.Context, request PutClientGroupRequestObject) (PutClientGroupResponseObject, error)
	// List custom DNS entries
	// (GET /custom-dns)
	ListCustomDNSEntries(ctx context.Context, request ListCustomDNSEntriesRequestObject) (ListCustomDNSEntriesResponseObject, error)
	// Create a custom DNS entry
	// (POST /custom-dns)
	CreateCustomDNSEntry(ctx context.Context, request CreateCustomDNSEntryRequestObject) (CreateCustomDNSEntryResponseObject, error)
	// Delete a custom DNS entry
	// (DELETE /custom-dns/{id})
	DeleteCustomDNSEntry(ctx context.Context, request DeleteCustomDNSEntryRequestObject) (DeleteCustomDNSEntryResponseObject, error)
	// Get a custom DNS entry by ID
	// (GET /custom-dns/{id})
	GetCustomDNSEntry(ctx context.Context, request GetCustomDNSEntryRequestObject) (GetCustomDNSEntryResponseObject, error)
	// Update a custom DNS entry
	// (PUT /custom-dns/{id})
	UpdateCustomDNSEntry(ctx context.Context, request UpdateCustomDNSEntryRequestObject) (UpdateCustomDNSEntryResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ApplyConfig operation middleware
func (sh *strictHandler) ApplyConfig(w http.ResponseWriter, r *http.Request) {
	var request ApplyConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyConfig(ctx, request.(ApplyConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyConfigResponseObject); ok {
		if err := validResponse.VisitApplyConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBlockSettings operation middleware
func (sh *strictHandler) GetBlockSettings(w http.ResponseWriter, r *http.Request) {
	var request GetBlockSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBlockSettings(ctx, request.(GetBlockSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBlockSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBlockSettingsResponseObject); ok {
		if err := validResponse.VisitGetBlockSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutBlockSettings operation middleware
func (sh *strictHandler) PutBlockSettings(w http.ResponseWriter, r *http.Request) {
	var request PutBlockSettingsRequestObject

	var body PutBlockSettingsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutBlockSettings(ctx, request.(PutBlockSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutBlockSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutBlockSettingsResponseObject); ok {
		if err := validResponse.VisitPutBlockSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBlocklistSources operation middleware
func (sh *strictHandler) ListBlocklistSources(w http.ResponseWriter, r *http.Request, params ListBlocklistSourcesParams) {
	var request ListBlocklistSourcesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBlocklistSources(ctx, request.(ListBlocklistSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBlocklistSources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBlocklistSourcesResponseObject); ok {
		if err := validResponse.VisitListBlocklistSourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateBlocklistSource operation middleware
func (sh *strictHandler) CreateBlocklistSource(w http.ResponseWriter, r *http.Request) {
	var request CreateBlocklistSourceRequestObject

	var body CreateBlocklistSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBlocklistSource(ctx, request.(CreateBlocklistSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBlocklistSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateBlocklistSourceResponseObject); ok {
		if err := validResponse.VisitCreateBlocklistSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteBlocklistSource operation middleware
func (sh *strictHandler) DeleteBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID) {
	var request DeleteBlocklistSourceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteBlocklistSource(ctx, request.(DeleteBlocklistSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteBlocklistSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteBlocklistSourceResponseObject); ok {
		if err := validResponse.VisitDeleteBlocklistSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBlocklistSource operation middleware
func (sh *strictHandler) GetBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID) {
	var request GetBlocklistSourceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBlocklistSource(ctx, request.(GetBlocklistSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBlocklistSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBlocklistSourceResponseObject); ok {
		if err := validResponse.VisitGetBlocklistSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateBlocklistSource operation middleware
func (sh *strictHandler) UpdateBlocklistSource(w http.ResponseWriter, r *http.Request, id ResourceID) {
	var request UpdateBlocklistSourceRequestObject

	request.Id = id

	var body UpdateBlocklistSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateBlocklistSource(ctx, request.(UpdateBlocklistSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateBlocklistSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateBlocklistSourceResponseObject); ok {
		if err := validResponse.VisitUpdateBlocklistSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListClientGroups operation middleware
func (sh *strictHandler) ListClientGroups(w http.ResponseWriter, r *http.Request) {
	var request ListClientGroupsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClientGroups(ctx, request.(ListClientGroupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClientGroups")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClientGroupsResponseObject); ok {
		if err := validResponse.VisitListClientGroupsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteClientGroup operation middleware
func (sh *strictHandler) DeleteClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName) {
	var request DeleteClientGroupRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteClientGroup(ctx, request.(DeleteClientGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteClientGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteClientGroupResponseObject); ok {
		if err := validResponse.VisitDeleteClientGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetClientGroup operation middleware
func (sh *strictHandler) GetClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName) {
	var request GetClientGroupRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClientGroup(ctx, request.(GetClientGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClientGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClientGroupResponseObject); ok {
		if err := validResponse.VisitGetClientGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutClientGroup operation middleware
func (sh *strictHandler) PutClientGroup(w http.ResponseWriter, r *http.Request, name ClientGroupName) {
	var request PutClientGroupRequestObject

	request.Name = name

	var body PutClientGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutClientGroup(ctx, request.(PutClientGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutClientGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutClientGroupResponseObject); ok {
		if err := validResponse.VisitPutClientGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCustomDNSEntries operation middleware
func (sh *strictHandler) ListCustomDNSEntries(w http.ResponseWriter, r *http.Request) {
	var request ListCustomDNSEntriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCustomDNSEntries(ctx, request.(ListCustomDNSEntriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCustomDNSEntries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCustomDNSEntriesResponseObject); ok {
		if err := validResponse.VisitListCustomDNSEntriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCustomDNSEntry operation middleware
func (sh *strictHandler) CreateCustomDNSEntry(w http.ResponseWriter, r *http.Request) {
	var request CreateCustomDNSEntryRequestObject

	var body CreateCustomDNSEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCustomDNSEntry(ctx, request.(CreateCustomDNSEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCustomDNSEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCustomDNSEntryResponseObject); ok {
		if err := validResponse.VisitCreateCustomDNSEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCustomDNSEntry operation middleware
func (sh *strictHandler) DeleteCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID) {
	var request DeleteCustomDNSEntryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCustomDNSEntry(ctx, request.(DeleteCustomDNSEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCustomDNSEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCustomDNSEntryResponseObject); ok {
		if err := validResponse.VisitDeleteCustomDNSEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCustomDNSEntry operation middleware
func (sh *strictHandler) GetCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID) {
	var request GetCustomDNSEntryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCustomDNSEntry(ctx, request.(GetCustomDNSEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCustomDNSEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCustomDNSEntryResponseObject); ok {
		if err := validResponse.VisitGetCustomDNSEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCustomDNSEntry operation middleware
func (sh *strictHandler) UpdateCustomDNSEntry(w http.ResponseWriter, r *http.Request, id ResourceID) {
	var request UpdateCustomDNSEntryRequestObject

	request.Id = id

	var body UpdateCustomDNSEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCustomDNSEntry(ctx, request.(UpdateCustomDNSEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCustomDNSEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCustomDNSEntryResponseObject); ok {
		if err := validResponse.VisitUpdateCustomDNSEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
