// Package configapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package configapi

// Defines values for ApplyResponseStatus.
const (
	Error ApplyResponseStatus = "error"
	Ok    ApplyResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the ApplyResponseStatus enum.
func (e ApplyResponseStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for BlocklistSourceListType.
const (
	BlocklistSourceListTypeAllow BlocklistSourceListType = "allow"
	BlocklistSourceListTypeDeny  BlocklistSourceListType = "deny"
)

// Valid indicates whether the value is a known member of the BlocklistSourceListType enum.
func (e BlocklistSourceListType) Valid() bool {
	switch e {
	case BlocklistSourceListTypeAllow:
		return true
	case BlocklistSourceListTypeDeny:
		return true
	default:
		return false
	}
}

// Defines values for BlocklistSourceSourceType.
const (
	BlocklistSourceSourceTypeFile BlocklistSourceSourceType = "file"
	BlocklistSourceSourceTypeHttp BlocklistSourceSourceType = "http"
	BlocklistSourceSourceTypeText BlocklistSourceSourceType = "text"
)

// Valid indicates whether the value is a known member of the BlocklistSourceSourceType enum.
func (e BlocklistSourceSourceType) Valid() bool {
	switch e {
	case BlocklistSourceSourceTypeFile:
		return true
	case BlocklistSourceSourceTypeHttp:
		return true
	case BlocklistSourceSourceTypeText:
		return true
	default:
		return false
	}
}

// Defines values for BlocklistSourceInputListType.
const (
	BlocklistSourceInputListTypeAllow BlocklistSourceInputListType = "allow"
	BlocklistSourceInputListTypeDeny  BlocklistSourceInputListType = "deny"
)

// Valid indicates whether the value is a known member of the BlocklistSourceInputListType enum.
func (e BlocklistSourceInputListType) Valid() bool {
	switch e {
	case BlocklistSourceInputListTypeAllow:
		return true
	case BlocklistSourceInputListTypeDeny:
		return true
	default:
		return false
	}
}

// Defines values for BlocklistSourceInputSourceType.
const (
	BlocklistSourceInputSourceTypeFile BlocklistSourceInputSourceType = "file"
	BlocklistSourceInputSourceTypeHttp BlocklistSourceInputSourceType = "http"
	BlocklistSourceInputSourceTypeText BlocklistSourceInputSourceType = "text"
)

// Valid indicates whether the value is a known member of the BlocklistSourceInputSourceType enum.
func (e BlocklistSourceInputSourceType) Valid() bool {
	switch e {
	case BlocklistSourceInputSourceTypeFile:
		return true
	case BlocklistSourceInputSourceTypeHttp:
		return true
	case BlocklistSourceInputSourceTypeText:
		return true
	default:
		return false
	}
}

// Defines values for CustomDNSEntryRecordType.
const (
	CustomDNSEntryRecordTypeA     CustomDNSEntryRecordType = "A"
	CustomDNSEntryRecordTypeAAAA  CustomDNSEntryRecordType = "AAAA"
	CustomDNSEntryRecordTypeCNAME CustomDNSEntryRecordType = "CNAME"
)

// Valid indicates whether the value is a known member of the CustomDNSEntryRecordType enum.
func (e CustomDNSEntryRecordType) Valid() bool {
	switch e {
	case CustomDNSEntryRecordTypeA:
		return true
	case CustomDNSEntryRecordTypeAAAA:
		return true
	case CustomDNSEntryRecordTypeCNAME:
		return true
	default:
		return false
	}
}

// Defines values for CustomDNSEntryInputRecordType.
const (
	CustomDNSEntryInputRecordTypeA     CustomDNSEntryInputRecordType = "A"
	CustomDNSEntryInputRecordTypeAAAA  CustomDNSEntryInputRecordType = "AAAA"
	CustomDNSEntryInputRecordTypeCNAME CustomDNSEntryInputRecordType = "CNAME"
)

// Valid indicates whether the value is a known member of the CustomDNSEntryInputRecordType enum.
func (e CustomDNSEntryInputRecordType) Valid() bool {
	switch e {
	case CustomDNSEntryInputRecordTypeA:
		return true
	case CustomDNSEntryInputRecordTypeAAAA:
		return true
	case CustomDNSEntryInputRecordTypeCNAME:
		return true
	default:
		return false
	}
}

// Defines values for DomainEntryEntryType.
const (
	DomainEntryEntryTypeExactAllow DomainEntryEntryType = "exact_allow"
	DomainEntryEntryTypeExactDeny  DomainEntryEntryType = "exact_deny"
	DomainEntryEntryTypeRegexAllow DomainEntryEntryType = "regex_allow"
	DomainEntryEntryTypeRegexDeny  DomainEntryEntryType = "regex_deny"
)

// Valid indicates whether the value is a known member of the DomainEntryEntryType enum.
func (e DomainEntryEntryType) Valid() bool {
	switch e {
	case DomainEntryEntryTypeExactAllow:
		return true
	case DomainEntryEntryTypeExactDeny:
		return true
	case DomainEntryEntryTypeRegexAllow:
		return true
	case DomainEntryEntryTypeRegexDeny:
		return true
	default:
		return false
	}
}

// Defines values for DomainEntryInputEntryType.
const (
	DomainEntryInputEntryTypeExactAllow DomainEntryInputEntryType = "exact_allow"
	DomainEntryInputEntryTypeExactDeny  DomainEntryInputEntryType = "exact_deny"
	DomainEntryInputEntryTypeRegexAllow DomainEntryInputEntryType = "regex_allow"
	DomainEntryInputEntryTypeRegexDeny  DomainEntryInputEntryType = "regex_deny"
)

// Valid indicates whether the value is a known member of the DomainEntryInputEntryType enum.
func (e DomainEntryInputEntryType) Valid() bool {
	switch e {
	case DomainEntryInputEntryTypeExactAllow:
		return true
	case DomainEntryInputEntryTypeExactDeny:
		return true
	case DomainEntryInputEntryTypeRegexAllow:
		return true
	case DomainEntryInputEntryTypeRegexDeny:
		return true
	default:
		return false
	}
}

// Defines values for UpstreamSettingsInitStrategy.
const (
	UpstreamSettingsInitStrategyBlocking    UpstreamSettingsInitStrategy = "blocking"
	UpstreamSettingsInitStrategyFailOnError UpstreamSettingsInitStrategy = "failOnError"
	UpstreamSettingsInitStrategyFast        UpstreamSettingsInitStrategy = "fast"
)

// Valid indicates whether the value is a known member of the UpstreamSettingsInitStrategy enum.
func (e UpstreamSettingsInitStrategy) Valid() bool {
	switch e {
	case UpstreamSettingsInitStrategyBlocking:
		return true
	case UpstreamSettingsInitStrategyFailOnError:
		return true
	case UpstreamSettingsInitStrategyFast:
		return true
	default:
		return false
	}
}

// Defines values for UpstreamSettingsStrategy.
const (
	UpstreamSettingsStrategyParallelBest UpstreamSettingsStrategy = "parallel_best"
	UpstreamSettingsStrategyRandom       UpstreamSettingsStrategy = "random"
	UpstreamSettingsStrategyStrict       UpstreamSettingsStrategy = "strict"
)

// Valid indicates whether the value is a known member of the UpstreamSettingsStrategy enum.
func (e UpstreamSettingsStrategy) Valid() bool {
	switch e {
	case UpstreamSettingsStrategyParallelBest:
		return true
	case UpstreamSettingsStrategyRandom:
		return true
	case UpstreamSettingsStrategyStrict:
		return true
	default:
		return false
	}
}

// Defines values for UpstreamSettingsInputInitStrategy.
const (
	UpstreamSettingsInputInitStrategyBlocking    UpstreamSettingsInputInitStrategy = "blocking"
	UpstreamSettingsInputInitStrategyFailOnError UpstreamSettingsInputInitStrategy = "failOnError"
	UpstreamSettingsInputInitStrategyFast        UpstreamSettingsInputInitStrategy = "fast"
)

// Valid indicates whether the value is a known member of the UpstreamSettingsInputInitStrategy enum.
func (e UpstreamSettingsInputInitStrategy) Valid() bool {
	switch e {
	case UpstreamSettingsInputInitStrategyBlocking:
		return true
	case UpstreamSettingsInputInitStrategyFailOnError:
		return true
	case UpstreamSettingsInputInitStrategyFast:
		return true
	default:
		return false
	}
}

// Defines values for UpstreamSettingsInputStrategy.
const (
	UpstreamSettingsInputStrategyParallelBest UpstreamSettingsInputStrategy = "parallel_best"
	UpstreamSettingsInputStrategyRandom       UpstreamSettingsInputStrategy = "random"
	UpstreamSettingsInputStrategyStrict       UpstreamSettingsInputStrategy = "strict"
)

// Valid indicates whether the value is a known member of the UpstreamSettingsInputStrategy enum.
func (e UpstreamSettingsInputStrategy) Valid() bool {
	switch e {
	case UpstreamSettingsInputStrategyParallelBest:
		return true
	case UpstreamSettingsInputStrategyRandom:
		return true
	case UpstreamSettingsInputStrategyStrict:
		return true
	default:
		return false
	}
}

// Defines values for ListBlocklistSourcesParamsListType.
const (
	Allow ListBlocklistSourcesParamsListType = "allow"
	Deny  ListBlocklistSourcesParamsListType = "deny"
)

// Valid indicates whether the value is a known member of the ListBlocklistSourcesParamsListType enum.
func (e ListBlocklistSourcesParamsListType) Valid() bool {
	switch e {
	case Allow:
		return true
	case Deny:
		return true
	default:
		return false
	}
}

// Defines values for ListDomainEntriesParamsEntryType.
const (
	ExactAllow ListDomainEntriesParamsEntryType = "exact_allow"
	ExactDeny  ListDomainEntriesParamsEntryType = "exact_deny"
	RegexAllow ListDomainEntriesParamsEntryType = "regex_allow"
	RegexDeny  ListDomainEntriesParamsEntryType = "regex_deny"
)

// Valid indicates whether the value is a known member of the ListDomainEntriesParamsEntryType enum.
func (e ListDomainEntriesParamsEntryType) Valid() bool {
	switch e {
	case ExactAllow:
		return true
	case ExactDeny:
		return true
	case RegexAllow:
		return true
	case RegexDeny:
		return true
	default:
		return false
	}
}

// ApplyResponse defines model for ApplyResponse.
type ApplyResponse struct {
	Error   *string             `json:"error,omitempty"`
	Message string              `json:"message"`
	Status  ApplyResponseStatus `json:"status"`
}

// ApplyResponseStatus defines model for ApplyResponse.Status.
type ApplyResponseStatus string

// BlockSettings defines model for BlockSettings.
type BlockSettings struct {
	BlockTtl  string `json:"block_ttl"`
	BlockType string `json:"block_type"`
}

// BlockSettingsInput defines model for BlockSettingsInput.
type BlockSettingsInput struct {
	BlockTtl  string `json:"block_ttl"`
	BlockType string `json:"block_type"`
}

// BlocklistSource defines model for BlocklistSource.
type BlocklistSource struct {
	Enabled    bool                      `json:"enabled"`
	GroupName  string                    `json:"group_name"`
	Id         int                       `json:"id"`
	ListType   BlocklistSourceListType   `json:"list_type"`
	Source     string                    `json:"source"`
	SourceType BlocklistSourceSourceType `json:"source_type"`
}

// BlocklistSourceListType defines model for BlocklistSource.ListType.
type BlocklistSourceListType string

// BlocklistSourceSourceType defines model for BlocklistSource.SourceType.
type BlocklistSourceSourceType string

// BlocklistSourceInput defines model for BlocklistSourceInput.
type BlocklistSourceInput struct {
	Enabled    bool                           `json:"enabled"`
	GroupName  string                         `json:"group_name"`
	ListType   BlocklistSourceInputListType   `json:"list_type"`
	Source     string                         `json:"source"`
	SourceType BlocklistSourceInputSourceType `json:"source_type"`
}

// BlocklistSourceInputListType defines model for BlocklistSourceInput.ListType.
type BlocklistSourceInputListType string

// BlocklistSourceInputSourceType defines model for BlocklistSourceInput.SourceType.
type BlocklistSourceInputSourceType string

// ClientGroup defines model for ClientGroup.
type ClientGroup struct {
	Clients []string `json:"clients"`
	Groups  []string `json:"groups"`
	Id      int      `json:"id"`
	Name    string   `json:"name"`
	Slug    string   `json:"slug"`
}

// ClientGroupInput defines model for ClientGroupInput.
type ClientGroupInput struct {
	Clients *[]string `json:"clients,omitempty"`
	Groups  *[]string `json:"groups,omitempty"`
}

// CustomDNSEntry defines model for CustomDNSEntry.
type CustomDNSEntry struct {
	Domain     string                   `json:"domain"`
	Enabled    bool                     `json:"enabled"`
	Id         int                      `json:"id"`
	RecordType CustomDNSEntryRecordType `json:"record_type"`
	Ttl        int                      `json:"ttl"`
	Value      string                   `json:"value"`
}

// CustomDNSEntryRecordType defines model for CustomDNSEntry.RecordType.
type CustomDNSEntryRecordType string

// CustomDNSEntryInput defines model for CustomDNSEntryInput.
type CustomDNSEntryInput struct {
	Domain     string                        `json:"domain"`
	Enabled    bool                          `json:"enabled"`
	RecordType CustomDNSEntryInputRecordType `json:"record_type"`
	Ttl        int                           `json:"ttl"`
	Value      string                        `json:"value"`
}

// CustomDNSEntryInputRecordType defines model for CustomDNSEntryInput.RecordType.
type CustomDNSEntryInputRecordType string

// DomainEntry defines model for DomainEntry.
type DomainEntry struct {
	Comment   string               `json:"comment"`
	Domain    string               `json:"domain"`
	Enabled   bool                 `json:"enabled"`
	EntryType DomainEntryEntryType `json:"entry_type"`
	GroupName string               `json:"group_name"`
	Id        int                  `json:"id"`
}

// DomainEntryEntryType defines model for DomainEntry.EntryType.
type DomainEntryEntryType string

// DomainEntryInput defines model for DomainEntryInput.
type DomainEntryInput struct {
	Comment   *string                   `json:"comment,omitempty"`
	Domain    string                    `json:"domain"`
	Enabled   bool                      `json:"enabled"`
	EntryType DomainEntryInputEntryType `json:"entry_type"`
}

// DomainEntryInputEntryType defines model for DomainEntryInput.EntryType.
type DomainEntryInputEntryType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// UpstreamGroup defines model for UpstreamGroup.
type UpstreamGroup struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// UpstreamServer defines model for UpstreamServer.
type UpstreamServer struct {
	Enabled   bool   `json:"enabled"`
	GroupName string `json:"group_name"`
	Id        int    `json:"id"`
	Position  int    `json:"position"`

	// Url Upstream server in `[net:]host[:port][/path][#commonName]` form, or a DNS stamp (`sdns://...`). Supported `net` prefixes are `tcp+udp` (default when omitted), `tcp-tls`, `https:` and `quic:`. For the latter two the `//` after the colon is optional, so `quic://dns.adguard.com` is accepted as well (AdGuard compatibility).
	Url string `json:"url"`
}

// UpstreamServerInput defines model for UpstreamServerInput.
type UpstreamServerInput struct {
	Enabled  bool `json:"enabled"`
	Position *int `json:"position,omitempty"`

	// Url Upstream server in `[net:]host[:port][/path][#commonName]` form, or a DNS stamp (`sdns://...`). Supported `net` prefixes are `tcp+udp` (default when omitted), `tcp-tls`, `https:` and `quic:`. For the latter two the `//` after the colon is optional, so `quic://dns.adguard.com` is accepted as well (AdGuard compatibility).
	Url string `json:"url"`
}

// UpstreamSettings defines model for UpstreamSettings.
type UpstreamSettings struct {
	InitStrategy UpstreamSettingsInitStrategy `json:"init_strategy"`
	Strategy     UpstreamSettingsStrategy     `json:"strategy"`
	Timeout      string                       `json:"timeout"`
	UserAgent    string                       `json:"user_agent"`
}

// UpstreamSettingsInitStrategy defines model for UpstreamSettings.InitStrategy.
type UpstreamSettingsInitStrategy string

// UpstreamSettingsStrategy defines model for UpstreamSettings.Strategy.
type UpstreamSettingsStrategy string

// UpstreamSettingsInput defines model for UpstreamSettingsInput.
type UpstreamSettingsInput struct {
	InitStrategy UpstreamSettingsInputInitStrategy `json:"init_strategy"`
	Strategy     UpstreamSettingsInputStrategy     `json:"strategy"`
	Timeout      string                            `json:"timeout"`
	UserAgent    string                            `json:"user_agent"`
}

// UpstreamSettingsInputInitStrategy defines model for UpstreamSettingsInput.InitStrategy.
type UpstreamSettingsInputInitStrategy string

// UpstreamSettingsInputStrategy defines model for UpstreamSettingsInput.Strategy.
type UpstreamSettingsInputStrategy string

// ClientGroupName defines model for ClientGroupName.
type ClientGroupName = string

// ResourceID defines model for ResourceID.
type ResourceID = int

// UpstreamGroupName defines model for UpstreamGroupName.
type UpstreamGroupName = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListBlocklistSourcesParams defines parameters for ListBlocklistSources.
type ListBlocklistSourcesParams struct {
	GroupName *string                             `form:"group_name,omitempty" json:"group_name,omitempty"`
	ListType  *ListBlocklistSourcesParamsListType `form:"list_type,omitempty" json:"list_type,omitempty"`
}

// ListBlocklistSourcesParamsListType defines parameters for ListBlocklistSources.
type ListBlocklistSourcesParamsListType string

// ListDomainEntriesParams defines parameters for ListDomainEntries.
type ListDomainEntriesParams struct {
	EntryType *ListDomainEntriesParamsEntryType `form:"entry_type,omitempty" json:"entry_type,omitempty"`
}

// ListDomainEntriesParamsEntryType defines parameters for ListDomainEntries.
type ListDomainEntriesParamsEntryType string

// PutBlockSettingsJSONRequestBody defines body for PutBlockSettings for application/json ContentType.
type PutBlockSettingsJSONRequestBody = BlockSettingsInput

// CreateBlocklistSourceJSONRequestBody defines body for CreateBlocklistSource for application/json ContentType.
type CreateBlocklistSourceJSONRequestBody = BlocklistSourceInput

// UpdateBlocklistSourceJSONRequestBody defines body for UpdateBlocklistSource for application/json ContentType.
type UpdateBlocklistSourceJSONRequestBody = BlocklistSourceInput

// PutClientGroupJSONRequestBody defines body for PutClientGroup for application/json ContentType.
type PutClientGroupJSONRequestBody = ClientGroupInput

// CreateCustomDNSEntryJSONRequestBody defines body for CreateCustomDNSEntry for application/json ContentType.
type CreateCustomDNSEntryJSONRequestBody = CustomDNSEntryInput

// UpdateCustomDNSEntryJSONRequestBody defines body for UpdateCustomDNSEntry for application/json ContentType.
type UpdateCustomDNSEntryJSONRequestBody = CustomDNSEntryInput

// CreateDomainEntryJSONRequestBody defines body for CreateDomainEntry for application/json ContentType.
type CreateDomainEntryJSONRequestBody = DomainEntryInput

// UpdateDomainEntryJSONRequestBody defines body for UpdateDomainEntry for application/json ContentType.
type UpdateDomainEntryJSONRequestBody = DomainEntryInput

// CreateUpstreamServerJSONRequestBody defines body for CreateUpstreamServer for application/json ContentType.
type CreateUpstreamServerJSONRequestBody = UpstreamServerInput

// UpdateUpstreamServerJSONRequestBody defines body for UpdateUpstreamServer for application/json ContentType.
type UpdateUpstreamServerJSONRequestBody = UpstreamServerInput

// PutUpstreamSettingsJSONRequestBody defines body for PutUpstreamSettings for application/json ContentType.
type PutUpstreamSettingsJSONRequestBody = UpstreamSettingsInput
