// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExpiringCache creates a new instance of MockExpiringCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpiringCache[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpiringCache[T] {
	mock := &MockExpiringCache[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExpiringCache is an autogenerated mock type for the ExpiringCache type
type MockExpiringCache[T any] struct {
	mock.Mock
}

type MockExpiringCache_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockExpiringCache[T]) EXPECT() *MockExpiringCache_Expecter[T] {
	return &MockExpiringCache_Expecter[T]{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockExpiringCache
func (_mock *MockExpiringCache[T]) Clear() {
	_mock.Called()
	return
}

// MockExpiringCache_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockExpiringCache_Clear_Call[T any] struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockExpiringCache_Expecter[T]) Clear() *MockExpiringCache_Clear_Call[T] {
	return &MockExpiringCache_Clear_Call[T]{Call: _e.mock.On("Clear")}
}

func (_c *MockExpiringCache_Clear_Call[T]) Run(run func()) *MockExpiringCache_Clear_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExpiringCache_Clear_Call[T]) Return() *MockExpiringCache_Clear_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockExpiringCache_Clear_Call[T]) RunAndReturn(run func()) *MockExpiringCache_Clear_Call[T] {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockExpiringCache
func (_mock *MockExpiringCache[T]) Get(key string) (*T, time.Duration) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *T
	var r1 time.Duration
	if returnFunc, ok := ret.Get(0).(func(string) (*T, time.Duration)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) time.Duration); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}
	return r0, r1
}

// MockExpiringCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExpiringCache_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockExpiringCache_Expecter[T]) Get(key interface{}) *MockExpiringCache_Get_Call[T] {
	return &MockExpiringCache_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *MockExpiringCache_Get_Call[T]) Run(run func(key string)) *MockExpiringCache_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpiringCache_Get_Call[T]) Return(val *T, expiration time.Duration) *MockExpiringCache_Get_Call[T] {
	_c.Call.Return(val, expiration)
	return _c
}

func (_c *MockExpiringCache_Get_Call[T]) RunAndReturn(run func(key string) (*T, time.Duration)) *MockExpiringCache_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockExpiringCache
func (_mock *MockExpiringCache[T]) Put(key string, val *T, expiration time.Duration) {
	_mock.Called(key, val, expiration)
	return
}

// MockExpiringCache_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockExpiringCache_Put_Call[T any] struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - key string
//   - val *T
//   - expiration time.Duration
func (_e *MockExpiringCache_Expecter[T]) Put(key interface{}, val interface{}, expiration interface{}) *MockExpiringCache_Put_Call[T] {
	return &MockExpiringCache_Put_Call[T]{Call: _e.mock.On("Put", key, val, expiration)}
}

func (_c *MockExpiringCache_Put_Call[T]) Run(run func(key string, val *T, expiration time.Duration)) *MockExpiringCache_Put_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *T
		if args[1] != nil {
			arg1 = args[1].(*T)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExpiringCache_Put_Call[T]) Return() *MockExpiringCache_Put_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockExpiringCache_Put_Call[T]) RunAndReturn(run func(key string, val *T, expiration time.Duration)) *MockExpiringCache_Put_Call[T] {
	_c.Run(run)
	return _c
}

// TotalCount provides a mock function for the type MockExpiringCache
func (_mock *MockExpiringCache[T]) TotalCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TotalCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockExpiringCache_TotalCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalCount'
type MockExpiringCache_TotalCount_Call[T any] struct {
	*mock.Call
}

// TotalCount is a helper method to define mock.On call
func (_e *MockExpiringCache_Expecter[T]) TotalCount() *MockExpiringCache_TotalCount_Call[T] {
	return &MockExpiringCache_TotalCount_Call[T]{Call: _e.mock.On("TotalCount")}
}

func (_c *MockExpiringCache_TotalCount_Call[T]) Run(run func()) *MockExpiringCache_TotalCount_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExpiringCache_TotalCount_Call[T]) Return(n int) *MockExpiringCache_TotalCount_Call[T] {
	_c.Call.Return(n)
	return _c
}

func (_c *MockExpiringCache_TotalCount_Call[T]) RunAndReturn(run func() int) *MockExpiringCache_TotalCount_Call[T] {
	_c.Call.Return(run)
	return _c
}
