package server

import (
	"context"
	"crypto/tls"
	"fmt"
	"net"
	"net/http"

	"github.com/0xERR0R/blocky/config"
	"github.com/quic-go/quic-go/http3"
)

// newH3TLSConfig clones base, forces TLS 1.3, and sets the h3 ALPN.
// The base config is not mutated.
func newH3TLSConfig(base *tls.Config) *tls.Config {
	cfg := base.Clone()
	cfg.MinVersion = tls.VersionTLS13

	return http3.ConfigureTLSConfig(cfg)
}

// http3Server is a thin wrapper around quic-go's http3.Server.
//
// Asymmetric with httpServer: there are N httpServers (one per TCP
// listener) but a single http3Server shared across all UDP listeners.
// The serve loop and shutdown watcher therefore live in Server.Start
// rather than on this wrapper. The wrapper exists for String() (log
// consistency) and as a handle for newAltSvcMiddleware.
type http3Server struct {
	inner http3.Server
	name  string
}

func newHTTP3Server(handler http.Handler, tlsCfg *tls.Config) *http3Server {
	return &http3Server{
		inner: http3.Server{
			TLSConfig: tlsCfg,
			Handler:   withCommonMiddleware(handler),
		},
		name: "http3",
	}
}

func (s *http3Server) String() string { return s.name }

// Close shuts down the underlying http3.Server. Safe to call multiple times.
func (s *http3Server) Close() error { return s.inner.Close() }

// newAltSvcMiddleware returns middleware that advertises HTTP/3
// availability on outgoing HTTPS responses via the Alt-Svc header.
// The header value is generated by quic-go from the h3 server's
// bound listeners; if none are bound yet, the header is empty and
// the error is intentionally ignored.
func newAltSvcMiddleware(h3 *http3Server) httpMiddleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			_ = h3.inner.SetQUICHeaders(w.Header())
			next.ServeHTTP(w, r)
		})
	}
}

// newUDPPacketConns opens one UDP packet conn per address. Returns
// an empty slice when addresses is empty.
func newUDPPacketConns(ctx context.Context, addresses config.ListenConfig) ([]net.PacketConn, error) {
	pcs := make([]net.PacketConn, 0, len(addresses))
	lc := &net.ListenConfig{}

	for _, address := range addresses {
		pc, err := lc.ListenPacket(ctx, "udp", address)
		if err != nil {
			for _, opened := range pcs {
				_ = opened.Close()
			}

			return nil, fmt.Errorf("start udp listener on %s failed: %w", address, err)
		}

		pcs = append(pcs, pc)
	}

	return pcs, nil
}
