package e2e

import (
	"context"
	"crypto/tls"
	"net"
	"net/http"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/quic-go/quic-go/http3"
	"github.com/testcontainers/testcontainers-go"
)

var _ = Describe("DoH3 functionality", Label("e2e"), func() {
	var (
		e2eNet *testcontainers.DockerNetwork
		blocky testcontainers.Container
		err    error
	)

	BeforeEach(func(ctx context.Context) {
		e2eNet = getRandomNetwork(ctx)

		_, err = createDNSMokkaContainer(ctx, "moka1", e2eNet,
			`A google/NOERROR("A 1.2.3.4 123")`)
		Expect(err).Should(Succeed())

		blocky, err = createBlockyContainerFromString(ctx, e2eNet, dedent(`
			upstreams:
			  groups:
			    default:
			      - moka1
			ports:
			  https: 4000
			http3:
			  enable: true
		`))
		Expect(err).Should(Succeed())
	})

	It("serves DoH over HTTP/3", func(ctx context.Context) {
		host, port, err := getContainerHostPort(ctx, blocky, "4000/udp")
		Expect(err).Should(Succeed())

		h3rt := &http3.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true, NextProtos: []string{"h3"}},
		}
		defer h3rt.Close()
		client := &http.Client{Transport: h3rt}

		url := "https://" + net.JoinHostPort(host, port) +
			"/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB"

		Eventually(func(g Gomega) {
			resp, err := client.Get(url)
			g.Expect(err).Should(Succeed())
			if err != nil {
				return
			}
			defer resp.Body.Close()

			g.Expect(resp.StatusCode).To(Equal(http.StatusOK))
			g.Expect(resp.Header.Get("Content-Type")).To(Equal("application/dns-message"))
		}, "30s", "1s").Should(Succeed())
	})

	It("advertises HTTP/3 via Alt-Svc on HTTPS responses", func(ctx context.Context) {
		// The Alt-Svc value generated by quic-go reflects the
		// container-internal UDP port (4000), not the host-mapped UDP
		// port that testcontainers picks. We only assert the h3=
		// token is present; rewriting the port for external clients
		// is out of scope for this test.
		host, port, err := getContainerHostPort(ctx, blocky, "4000/tcp")
		Expect(err).Should(Succeed())

		tr := &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		}
		client := &http.Client{Transport: tr}

		url := "https://" + net.JoinHostPort(host, port) +
			"/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB"

		Eventually(func(g Gomega) {
			resp, err := client.Get(url)
			g.Expect(err).Should(Succeed())
			if err != nil {
				return
			}
			defer resp.Body.Close()

			g.Expect(resp.Header.Get("Alt-Svc")).To(ContainSubstring("h3="))
		}, "10s", "1s").Should(Succeed())
	})
})
