// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package resolver

import (
	"fmt"
	"strings"
)

const (
	// ValidationResultSecure is a ValidationResult of type Secure.
	// Valid DNSSEC signatures and chain of trust
	ValidationResultSecure ValidationResult = iota
	// ValidationResultInsecure is a ValidationResult of type Insecure.
	// No DNSSEC (unsigned zone)
	ValidationResultInsecure
	// ValidationResultBogus is a ValidationResult of type Bogus.
	// Invalid DNSSEC (failed validation)
	ValidationResultBogus
	// ValidationResultIndeterminate is a ValidationResult of type Indeterminate.
	// Validation could not be completed
	ValidationResultIndeterminate
)

var ErrInvalidValidationResult = fmt.Errorf("not a valid ValidationResult, try [%s]", strings.Join(_ValidationResultNames, ", "))

const _ValidationResultName = "SecureInsecureBogusIndeterminate"

var _ValidationResultNames = []string{
	_ValidationResultName[0:6],
	_ValidationResultName[6:14],
	_ValidationResultName[14:19],
	_ValidationResultName[19:32],
}

// ValidationResultNames returns a list of possible string values of ValidationResult.
func ValidationResultNames() []string {
	tmp := make([]string, len(_ValidationResultNames))
	copy(tmp, _ValidationResultNames)
	return tmp
}

// ValidationResultValues returns a list of the values for ValidationResult
func ValidationResultValues() []ValidationResult {
	return []ValidationResult{
		ValidationResultSecure,
		ValidationResultInsecure,
		ValidationResultBogus,
		ValidationResultIndeterminate,
	}
}

var _ValidationResultMap = map[ValidationResult]string{
	ValidationResultSecure:        _ValidationResultName[0:6],
	ValidationResultInsecure:      _ValidationResultName[6:14],
	ValidationResultBogus:         _ValidationResultName[14:19],
	ValidationResultIndeterminate: _ValidationResultName[19:32],
}

// String implements the Stringer interface.
func (x ValidationResult) String() string {
	if str, ok := _ValidationResultMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ValidationResult(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ValidationResult) IsValid() bool {
	_, ok := _ValidationResultMap[x]
	return ok
}

var _ValidationResultValue = map[string]ValidationResult{
	_ValidationResultName[0:6]:   ValidationResultSecure,
	_ValidationResultName[6:14]:  ValidationResultInsecure,
	_ValidationResultName[14:19]: ValidationResultBogus,
	_ValidationResultName[19:32]: ValidationResultIndeterminate,
}

// ParseValidationResult attempts to convert a string to a ValidationResult.
func ParseValidationResult(name string) (ValidationResult, error) {
	if x, ok := _ValidationResultValue[name]; ok {
		return x, nil
	}
	return ValidationResult(0), fmt.Errorf("%s is %w", name, ErrInvalidValidationResult)
}

// MarshalText implements the text marshaller method.
func (x ValidationResult) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ValidationResult) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseValidationResult(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ValidationResult) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
