// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resolver

import (
	"context"
	"log/slog"

	"github.com/0xERR0R/blocky/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChainedResolver creates a new instance of MockChainedResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChainedResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChainedResolver {
	mock := &MockChainedResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChainedResolver is an autogenerated mock type for the ChainedResolver type
type MockChainedResolver struct {
	mock.Mock
}

type MockChainedResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChainedResolver) EXPECT() *MockChainedResolver_Expecter {
	return &MockChainedResolver_Expecter{mock: &_m.Mock}
}

// GetNext provides a mock function for the type MockChainedResolver
func (_mock *MockChainedResolver) GetNext() Resolver {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNext")
	}

	var r0 Resolver
	if returnFunc, ok := ret.Get(0).(func() Resolver); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Resolver)
		}
	}
	return r0
}

// MockChainedResolver_GetNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNext'
type MockChainedResolver_GetNext_Call struct {
	*mock.Call
}

// GetNext is a helper method to define mock.On call
func (_e *MockChainedResolver_Expecter) GetNext() *MockChainedResolver_GetNext_Call {
	return &MockChainedResolver_GetNext_Call{Call: _e.mock.On("GetNext")}
}

func (_c *MockChainedResolver_GetNext_Call) Run(run func()) *MockChainedResolver_GetNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChainedResolver_GetNext_Call) Return(resolver Resolver) *MockChainedResolver_GetNext_Call {
	_c.Call.Return(resolver)
	return _c
}

func (_c *MockChainedResolver_GetNext_Call) RunAndReturn(run func() Resolver) *MockChainedResolver_GetNext_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function for the type MockChainedResolver
func (_mock *MockChainedResolver) IsEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockChainedResolver_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockChainedResolver_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockChainedResolver_Expecter) IsEnabled() *MockChainedResolver_IsEnabled_Call {
	return &MockChainedResolver_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockChainedResolver_IsEnabled_Call) Run(run func()) *MockChainedResolver_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChainedResolver_IsEnabled_Call) Return(b bool) *MockChainedResolver_IsEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockChainedResolver_IsEnabled_Call) RunAndReturn(run func() bool) *MockChainedResolver_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// LogConfig provides a mock function for the type MockChainedResolver
func (_mock *MockChainedResolver) LogConfig(logger *slog.Logger) {
	_mock.Called(logger)
	return
}

// MockChainedResolver_LogConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogConfig'
type MockChainedResolver_LogConfig_Call struct {
	*mock.Call
}

// LogConfig is a helper method to define mock.On call
//   - logger *slog.Logger
func (_e *MockChainedResolver_Expecter) LogConfig(logger interface{}) *MockChainedResolver_LogConfig_Call {
	return &MockChainedResolver_LogConfig_Call{Call: _e.mock.On("LogConfig", logger)}
}

func (_c *MockChainedResolver_LogConfig_Call) Run(run func(logger *slog.Logger)) *MockChainedResolver_LogConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *slog.Logger
		if args[0] != nil {
			arg0 = args[0].(*slog.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChainedResolver_LogConfig_Call) Return() *MockChainedResolver_LogConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChainedResolver_LogConfig_Call) RunAndReturn(run func(logger *slog.Logger)) *MockChainedResolver_LogConfig_Call {
	_c.Run(run)
	return _c
}

// Next provides a mock function for the type MockChainedResolver
func (_mock *MockChainedResolver) Next(n Resolver) {
	_mock.Called(n)
	return
}

// MockChainedResolver_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockChainedResolver_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - n Resolver
func (_e *MockChainedResolver_Expecter) Next(n interface{}) *MockChainedResolver_Next_Call {
	return &MockChainedResolver_Next_Call{Call: _e.mock.On("Next", n)}
}

func (_c *MockChainedResolver_Next_Call) Run(run func(n Resolver)) *MockChainedResolver_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Resolver
		if args[0] != nil {
			arg0 = args[0].(Resolver)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChainedResolver_Next_Call) Return() *MockChainedResolver_Next_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChainedResolver_Next_Call) RunAndReturn(run func(n Resolver)) *MockChainedResolver_Next_Call {
	_c.Run(run)
	return _c
}

// Resolve provides a mock function for the type MockChainedResolver
func (_mock *MockChainedResolver) Resolve(ctx context.Context, req *model.Request) (*model.Response, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *model.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Request) (*model.Response, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Request) *model.Response); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChainedResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockChainedResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.Request
func (_e *MockChainedResolver_Expecter) Resolve(ctx interface{}, req interface{}) *MockChainedResolver_Resolve_Call {
	return &MockChainedResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, req)}
}

func (_c *MockChainedResolver_Resolve_Call) Run(run func(ctx context.Context, req *model.Request)) *MockChainedResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Request
		if args[1] != nil {
			arg1 = args[1].(*model.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChainedResolver_Resolve_Call) Return(response *model.Response, err error) *MockChainedResolver_Resolve_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockChainedResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, req *model.Request) (*model.Response, error)) *MockChainedResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockChainedResolver
func (_mock *MockChainedResolver) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockChainedResolver_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockChainedResolver_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockChainedResolver_Expecter) String() *MockChainedResolver_String_Call {
	return &MockChainedResolver_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockChainedResolver_String_Call) Run(run func()) *MockChainedResolver_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChainedResolver_String_Call) Return(s string) *MockChainedResolver_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockChainedResolver_String_Call) RunAndReturn(run func() string) *MockChainedResolver_String_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockChainedResolver
func (_mock *MockChainedResolver) Type() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockChainedResolver_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockChainedResolver_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockChainedResolver_Expecter) Type() *MockChainedResolver_Type_Call {
	return &MockChainedResolver_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockChainedResolver_Type_Call) Run(run func()) *MockChainedResolver_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChainedResolver_Type_Call) Return(s string) *MockChainedResolver_Type_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockChainedResolver_Type_Call) RunAndReturn(run func() string) *MockChainedResolver_Type_Call {
	_c.Call.Return(run)
	return _c
}
