// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lists

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileDownloader creates a new instance of MockFileDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileDownloader {
	mock := &MockFileDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileDownloader is an autogenerated mock type for the FileDownloader type
type MockFileDownloader struct {
	mock.Mock
}

type MockFileDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileDownloader) EXPECT() *MockFileDownloader_Expecter {
	return &MockFileDownloader_Expecter{mock: &_m.Mock}
}

// DownloadFile provides a mock function for the type MockFileDownloader
func (_mock *MockFileDownloader) DownloadFile(ctx context.Context, link string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, link)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, link)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileDownloader_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type MockFileDownloader_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - link string
func (_e *MockFileDownloader_Expecter) DownloadFile(ctx interface{}, link interface{}) *MockFileDownloader_DownloadFile_Call {
	return &MockFileDownloader_DownloadFile_Call{Call: _e.mock.On("DownloadFile", ctx, link)}
}

func (_c *MockFileDownloader_DownloadFile_Call) Run(run func(ctx context.Context, link string)) *MockFileDownloader_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileDownloader_DownloadFile_Call) Return(readCloser io.ReadCloser, err error) *MockFileDownloader_DownloadFile_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockFileDownloader_DownloadFile_Call) RunAndReturn(run func(ctx context.Context, link string) (io.ReadCloser, error)) *MockFileDownloader_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}
