// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

// ApiBlockingStatus defines model for api.BlockingStatus.
type ApiBlockingStatus struct {
	// AutoEnableInSec If blocking is temporary disabled: amount of seconds until blocking will be enabled
	AutoEnableInSec *int `json:"autoEnableInSec,omitempty"`

	// DisabledGroups Disabled group names
	DisabledGroups *[]string `json:"disabledGroups,omitempty"`

	// Enabled True if blocking is enabled
	Enabled bool `json:"enabled"`
}

// ApiCacheStats Current cache state (point-in-time, not windowed).
type ApiCacheStats struct {
	// Entries Current number of entries in the result cache.
	Entries int `json:"entries"`
}

// ApiHourPoint defines model for api.HourPoint.
type ApiHourPoint struct {
	Blocked int       `json:"blocked"`
	Hour    time.Time `json:"hour"`
	Queries int       `json:"queries"`
}

// ApiListCounts Current per-group list entry counts (point-in-time, not windowed).
type ApiListCounts struct {
	Allowlist map[string]int `json:"allowlist"`
	Denylist  map[string]int `json:"denylist"`
}

// ApiNameCount defines model for api.NameCount.
type ApiNameCount struct {
	Count int    `json:"count"`
	Name  string `json:"name"`
}

// ApiQueryRequest defines model for api.QueryRequest.
type ApiQueryRequest struct {
	// Query query for DNS request
	Query string `json:"query"`

	// Type request type (A, AAAA, ...)
	Type string `json:"type"`
}

// ApiQueryResult defines model for api.QueryResult.
type ApiQueryResult struct {
	// Reason blocky reason for resolution
	Reason string `json:"reason"`

	// Response actual DNS response
	Response string `json:"response"`

	// ResponseType response type (CACHED, BLOCKED, ...)
	ResponseType string `json:"responseType"`

	// ReturnCode DNS return code (NOERROR, NXDOMAIN, ...)
	ReturnCode string `json:"returnCode"`
}

// ApiStats In-memory DNS statistics snapshot.
type ApiStats struct {
	// ByQueryType Counts per DNS query type over the window (A, AAAA, ...).
	ByQueryType map[string]int `json:"byQueryType"`

	// ByResponseCode Counts per DNS response code over the window (NOERROR, NXDOMAIN, ...).
	ByResponseCode map[string]int `json:"byResponseCode"`

	// ByResponseType Raw per-RType counts over the window (CACHED, BLOCKED, ...).
	ByResponseType map[string]int `json:"byResponseType"`

	// Cache Current cache state (point-in-time, not windowed).
	Cache ApiCacheStats `json:"cache"`

	// End Snapshot time.
	End time.Time `json:"end"`

	// Lists Current per-group list entry counts (point-in-time, not windowed).
	Lists ApiListCounts `json:"lists"`

	// PerHour Per-hour time series over the window.
	PerHour []ApiHourPoint `json:"perHour"`

	// Start Start of the covered window for the windowed fields (not the gauges).
	Start time.Time `json:"start"`

	// Summary Curated outcome categories over the window (server computes the mapping).
	Summary           ApiStatsSummary `json:"summary"`
	TopBlockedDomains []ApiNameCount  `json:"topBlockedDomains"`
	TopClients        []ApiNameCount  `json:"topClients"`
	TopDomains        []ApiNameCount  `json:"topDomains"`
}

// ApiStatsSummary Curated outcome categories over the window (server computes the mapping).
type ApiStatsSummary struct {
	AvgResponseMs int     `json:"avgResponseMs"`
	Blocked       int     `json:"blocked"`
	CacheHitRate  float64 `json:"cacheHitRate"`
	Cached        int     `json:"cached"`
	Dropped       int     `json:"dropped"`
	Errors        int     `json:"errors"`
	Forwarded     int     `json:"forwarded"`
	Local         int     `json:"local"`

	// Queries Total queries received in the window.
	Queries int `json:"queries"`
}

// DisableBlockingParams defines parameters for DisableBlocking.
type DisableBlockingParams struct {
	// Duration duration of blocking (Example: 300s, 5m, 1h, 5m30s)
	Duration *string `form:"duration,omitempty" json:"duration,omitempty"`

	// Groups groups to disable (comma separated). If empty, disable all groups
	Groups *string `form:"groups,omitempty" json:"groups,omitempty"`
}

// QueryJSONRequestBody defines body for Query for application/json ContentType.
type QueryJSONRequestBody = ApiQueryRequest
