// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"
	"net"
	"time"

	"github.com/0xERR0R/blocky/config"
	"github.com/0xERR0R/blocky/model"
	"github.com/miekg/dns"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockingControl creates a new instance of MockBlockingControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockingControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockingControl {
	mock := &MockBlockingControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockingControl is an autogenerated mock type for the BlockingControl type
type MockBlockingControl struct {
	mock.Mock
}

type MockBlockingControl_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockingControl) EXPECT() *MockBlockingControl_Expecter {
	return &MockBlockingControl_Expecter{mock: &_m.Mock}
}

// BlockingStatus provides a mock function for the type MockBlockingControl
func (_mock *MockBlockingControl) BlockingStatus() BlockingStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BlockingStatus")
	}

	var r0 BlockingStatus
	if returnFunc, ok := ret.Get(0).(func() BlockingStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(BlockingStatus)
	}
	return r0
}

// MockBlockingControl_BlockingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockingStatus'
type MockBlockingControl_BlockingStatus_Call struct {
	*mock.Call
}

// BlockingStatus is a helper method to define mock.On call
func (_e *MockBlockingControl_Expecter) BlockingStatus() *MockBlockingControl_BlockingStatus_Call {
	return &MockBlockingControl_BlockingStatus_Call{Call: _e.mock.On("BlockingStatus")}
}

func (_c *MockBlockingControl_BlockingStatus_Call) Run(run func()) *MockBlockingControl_BlockingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockingControl_BlockingStatus_Call) Return(blockingStatus BlockingStatus) *MockBlockingControl_BlockingStatus_Call {
	_c.Call.Return(blockingStatus)
	return _c
}

func (_c *MockBlockingControl_BlockingStatus_Call) RunAndReturn(run func() BlockingStatus) *MockBlockingControl_BlockingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// DisableBlocking provides a mock function for the type MockBlockingControl
func (_mock *MockBlockingControl) DisableBlocking(ctx context.Context, duration time.Duration, disableGroups []string) error {
	ret := _mock.Called(ctx, duration, disableGroups)

	if len(ret) == 0 {
		panic("no return value specified for DisableBlocking")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, []string) error); ok {
		r0 = returnFunc(ctx, duration, disableGroups)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockingControl_DisableBlocking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableBlocking'
type MockBlockingControl_DisableBlocking_Call struct {
	*mock.Call
}

// DisableBlocking is a helper method to define mock.On call
//   - ctx context.Context
//   - duration time.Duration
//   - disableGroups []string
func (_e *MockBlockingControl_Expecter) DisableBlocking(ctx interface{}, duration interface{}, disableGroups interface{}) *MockBlockingControl_DisableBlocking_Call {
	return &MockBlockingControl_DisableBlocking_Call{Call: _e.mock.On("DisableBlocking", ctx, duration, disableGroups)}
}

func (_c *MockBlockingControl_DisableBlocking_Call) Run(run func(ctx context.Context, duration time.Duration, disableGroups []string)) *MockBlockingControl_DisableBlocking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlockingControl_DisableBlocking_Call) Return(err error) *MockBlockingControl_DisableBlocking_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockingControl_DisableBlocking_Call) RunAndReturn(run func(ctx context.Context, duration time.Duration, disableGroups []string) error) *MockBlockingControl_DisableBlocking_Call {
	_c.Call.Return(run)
	return _c
}

// EnableBlocking provides a mock function for the type MockBlockingControl
func (_mock *MockBlockingControl) EnableBlocking(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockBlockingControl_EnableBlocking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableBlocking'
type MockBlockingControl_EnableBlocking_Call struct {
	*mock.Call
}

// EnableBlocking is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlockingControl_Expecter) EnableBlocking(ctx interface{}) *MockBlockingControl_EnableBlocking_Call {
	return &MockBlockingControl_EnableBlocking_Call{Call: _e.mock.On("EnableBlocking", ctx)}
}

func (_c *MockBlockingControl_EnableBlocking_Call) Run(run func(ctx context.Context)) *MockBlockingControl_EnableBlocking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockingControl_EnableBlocking_Call) Return() *MockBlockingControl_EnableBlocking_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBlockingControl_EnableBlocking_Call) RunAndReturn(run func(ctx context.Context)) *MockBlockingControl_EnableBlocking_Call {
	_c.Run(run)
	return _c
}

// NewMockListRefresher creates a new instance of MockListRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListRefresher {
	mock := &MockListRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListRefresher is an autogenerated mock type for the ListRefresher type
type MockListRefresher struct {
	mock.Mock
}

type MockListRefresher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListRefresher) EXPECT() *MockListRefresher_Expecter {
	return &MockListRefresher_Expecter{mock: &_m.Mock}
}

// RefreshLists provides a mock function for the type MockListRefresher
func (_mock *MockListRefresher) RefreshLists(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RefreshLists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockListRefresher_RefreshLists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshLists'
type MockListRefresher_RefreshLists_Call struct {
	*mock.Call
}

// RefreshLists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListRefresher_Expecter) RefreshLists(ctx interface{}) *MockListRefresher_RefreshLists_Call {
	return &MockListRefresher_RefreshLists_Call{Call: _e.mock.On("RefreshLists", ctx)}
}

func (_c *MockListRefresher_RefreshLists_Call) Run(run func(ctx context.Context)) *MockListRefresher_RefreshLists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListRefresher_RefreshLists_Call) Return(err error) *MockListRefresher_RefreshLists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockListRefresher_RefreshLists_Call) RunAndReturn(run func(ctx context.Context) error) *MockListRefresher_RefreshLists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type MockQuerier
func (_mock *MockQuerier) Query(ctx context.Context, serverHost string, clientIP net.IP, question string, qType dns.Type) (*model.Response, error) {
	ret := _mock.Called(ctx, serverHost, clientIP, question, qType)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *model.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, net.IP, string, dns.Type) (*model.Response, error)); ok {
		return returnFunc(ctx, serverHost, clientIP, question, qType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, net.IP, string, dns.Type) *model.Response); ok {
		r0 = returnFunc(ctx, serverHost, clientIP, question, qType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, net.IP, string, dns.Type) error); ok {
		r1 = returnFunc(ctx, serverHost, clientIP, question, qType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockQuerier_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - serverHost string
//   - clientIP net.IP
//   - question string
//   - qType dns.Type
func (_e *MockQuerier_Expecter) Query(ctx interface{}, serverHost interface{}, clientIP interface{}, question interface{}, qType interface{}) *MockQuerier_Query_Call {
	return &MockQuerier_Query_Call{Call: _e.mock.On("Query", ctx, serverHost, clientIP, question, qType)}
}

func (_c *MockQuerier_Query_Call) Run(run func(ctx context.Context, serverHost string, clientIP net.IP, question string, qType dns.Type)) *MockQuerier_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 net.IP
		if args[2] != nil {
			arg2 = args[2].(net.IP)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 dns.Type
		if args[4] != nil {
			arg4 = args[4].(dns.Type)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockQuerier_Query_Call) Return(response *model.Response, err error) *MockQuerier_Query_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockQuerier_Query_Call) RunAndReturn(run func(ctx context.Context, serverHost string, clientIP net.IP, question string, qType dns.Type) (*model.Response, error)) *MockQuerier_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheControl creates a new instance of MockCacheControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheControl {
	mock := &MockCacheControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheControl is an autogenerated mock type for the CacheControl type
type MockCacheControl struct {
	mock.Mock
}

type MockCacheControl_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheControl) EXPECT() *MockCacheControl_Expecter {
	return &MockCacheControl_Expecter{mock: &_m.Mock}
}

// FlushCaches provides a mock function for the type MockCacheControl
func (_mock *MockCacheControl) FlushCaches(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockCacheControl_FlushCaches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushCaches'
type MockCacheControl_FlushCaches_Call struct {
	*mock.Call
}

// FlushCaches is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacheControl_Expecter) FlushCaches(ctx interface{}) *MockCacheControl_FlushCaches_Call {
	return &MockCacheControl_FlushCaches_Call{Call: _e.mock.On("FlushCaches", ctx)}
}

func (_c *MockCacheControl_FlushCaches_Call) Run(run func(ctx context.Context)) *MockCacheControl_FlushCaches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCacheControl_FlushCaches_Call) Return() *MockCacheControl_FlushCaches_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheControl_FlushCaches_Call) RunAndReturn(run func(ctx context.Context)) *MockCacheControl_FlushCaches_Call {
	_c.Run(run)
	return _c
}

// NewMockResolverLookup creates a new instance of MockResolverLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolverLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolverLookup {
	mock := &MockResolverLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolverLookup is an autogenerated mock type for the ResolverLookup type
type MockResolverLookup struct {
	mock.Mock
}

type MockResolverLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolverLookup) EXPECT() *MockResolverLookup_Expecter {
	return &MockResolverLookup_Expecter{mock: &_m.Mock}
}

// BlockingControl provides a mock function for the type MockResolverLookup
func (_mock *MockResolverLookup) BlockingControl() (BlockingControl, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BlockingControl")
	}

	var r0 BlockingControl
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (BlockingControl, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() BlockingControl); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(BlockingControl)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolverLookup_BlockingControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockingControl'
type MockResolverLookup_BlockingControl_Call struct {
	*mock.Call
}

// BlockingControl is a helper method to define mock.On call
func (_e *MockResolverLookup_Expecter) BlockingControl() *MockResolverLookup_BlockingControl_Call {
	return &MockResolverLookup_BlockingControl_Call{Call: _e.mock.On("BlockingControl")}
}

func (_c *MockResolverLookup_BlockingControl_Call) Run(run func()) *MockResolverLookup_BlockingControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverLookup_BlockingControl_Call) Return(blockingControl BlockingControl, err error) *MockResolverLookup_BlockingControl_Call {
	_c.Call.Return(blockingControl, err)
	return _c
}

func (_c *MockResolverLookup_BlockingControl_Call) RunAndReturn(run func() (BlockingControl, error)) *MockResolverLookup_BlockingControl_Call {
	_c.Call.Return(run)
	return _c
}

// CacheControl provides a mock function for the type MockResolverLookup
func (_mock *MockResolverLookup) CacheControl() (CacheControl, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CacheControl")
	}

	var r0 CacheControl
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (CacheControl, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() CacheControl); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CacheControl)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolverLookup_CacheControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheControl'
type MockResolverLookup_CacheControl_Call struct {
	*mock.Call
}

// CacheControl is a helper method to define mock.On call
func (_e *MockResolverLookup_Expecter) CacheControl() *MockResolverLookup_CacheControl_Call {
	return &MockResolverLookup_CacheControl_Call{Call: _e.mock.On("CacheControl")}
}

func (_c *MockResolverLookup_CacheControl_Call) Run(run func()) *MockResolverLookup_CacheControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverLookup_CacheControl_Call) Return(cacheControl CacheControl, err error) *MockResolverLookup_CacheControl_Call {
	_c.Call.Return(cacheControl, err)
	return _c
}

func (_c *MockResolverLookup_CacheControl_Call) RunAndReturn(run func() (CacheControl, error)) *MockResolverLookup_CacheControl_Call {
	_c.Call.Return(run)
	return _c
}

// ListRefresher provides a mock function for the type MockResolverLookup
func (_mock *MockResolverLookup) ListRefresher() (ListRefresher, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListRefresher")
	}

	var r0 ListRefresher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (ListRefresher, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() ListRefresher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ListRefresher)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolverLookup_ListRefresher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefresher'
type MockResolverLookup_ListRefresher_Call struct {
	*mock.Call
}

// ListRefresher is a helper method to define mock.On call
func (_e *MockResolverLookup_Expecter) ListRefresher() *MockResolverLookup_ListRefresher_Call {
	return &MockResolverLookup_ListRefresher_Call{Call: _e.mock.On("ListRefresher")}
}

func (_c *MockResolverLookup_ListRefresher_Call) Run(run func()) *MockResolverLookup_ListRefresher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverLookup_ListRefresher_Call) Return(listRefresher ListRefresher, err error) *MockResolverLookup_ListRefresher_Call {
	_c.Call.Return(listRefresher, err)
	return _c
}

func (_c *MockResolverLookup_ListRefresher_Call) RunAndReturn(run func() (ListRefresher, error)) *MockResolverLookup_ListRefresher_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockResolverLookup
func (_mock *MockResolverLookup) Query(ctx context.Context, serverHost string, clientIP net.IP, question string, qType dns.Type) (*model.Response, error) {
	ret := _mock.Called(ctx, serverHost, clientIP, question, qType)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *model.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, net.IP, string, dns.Type) (*model.Response, error)); ok {
		return returnFunc(ctx, serverHost, clientIP, question, qType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, net.IP, string, dns.Type) *model.Response); ok {
		r0 = returnFunc(ctx, serverHost, clientIP, question, qType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, net.IP, string, dns.Type) error); ok {
		r1 = returnFunc(ctx, serverHost, clientIP, question, qType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolverLookup_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockResolverLookup_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - serverHost string
//   - clientIP net.IP
//   - question string
//   - qType dns.Type
func (_e *MockResolverLookup_Expecter) Query(ctx interface{}, serverHost interface{}, clientIP interface{}, question interface{}, qType interface{}) *MockResolverLookup_Query_Call {
	return &MockResolverLookup_Query_Call{Call: _e.mock.On("Query", ctx, serverHost, clientIP, question, qType)}
}

func (_c *MockResolverLookup_Query_Call) Run(run func(ctx context.Context, serverHost string, clientIP net.IP, question string, qType dns.Type)) *MockResolverLookup_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 net.IP
		if args[2] != nil {
			arg2 = args[2].(net.IP)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 dns.Type
		if args[4] != nil {
			arg4 = args[4].(dns.Type)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockResolverLookup_Query_Call) Return(response *model.Response, err error) *MockResolverLookup_Query_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockResolverLookup_Query_Call) RunAndReturn(run func(ctx context.Context, serverHost string, clientIP net.IP, question string, qType dns.Type) (*model.Response, error)) *MockResolverLookup_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigReloader creates a new instance of MockConfigReloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigReloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigReloader {
	mock := &MockConfigReloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigReloader is an autogenerated mock type for the ConfigReloader type
type MockConfigReloader struct {
	mock.Mock
}

type MockConfigReloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigReloader) EXPECT() *MockConfigReloader_Expecter {
	return &MockConfigReloader_Expecter{mock: &_m.Mock}
}

// ActiveConfig provides a mock function for the type MockConfigReloader
func (_mock *MockConfigReloader) ActiveConfig() *config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ActiveConfig")
	}

	var r0 *config.Config
	if returnFunc, ok := ret.Get(0).(func() *config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}
	return r0
}

// MockConfigReloader_ActiveConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveConfig'
type MockConfigReloader_ActiveConfig_Call struct {
	*mock.Call
}

// ActiveConfig is a helper method to define mock.On call
func (_e *MockConfigReloader_Expecter) ActiveConfig() *MockConfigReloader_ActiveConfig_Call {
	return &MockConfigReloader_ActiveConfig_Call{Call: _e.mock.On("ActiveConfig")}
}

func (_c *MockConfigReloader_ActiveConfig_Call) Run(run func()) *MockConfigReloader_ActiveConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReloader_ActiveConfig_Call) Return(config1 *config.Config) *MockConfigReloader_ActiveConfig_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *MockConfigReloader_ActiveConfig_Call) RunAndReturn(run func() *config.Config) *MockConfigReloader_ActiveConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Reload provides a mock function for the type MockConfigReloader
func (_mock *MockConfigReloader) Reload() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigReloader_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MockConfigReloader_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
func (_e *MockConfigReloader_Expecter) Reload() *MockConfigReloader_Reload_Call {
	return &MockConfigReloader_Reload_Call{Call: _e.mock.On("Reload")}
}

func (_c *MockConfigReloader_Reload_Call) Run(run func()) *MockConfigReloader_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReloader_Reload_Call) Return(err error) *MockConfigReloader_Reload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigReloader_Reload_Call) RunAndReturn(run func() error) *MockConfigReloader_Reload_Call {
	_c.Call.Return(run)
	return _c
}
