name: Delete workflow runs

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  del_runs:
    name: Delete workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete skipped
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: skipped
      
      - name: Delete cancelled
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: cancelled
      
      - name: Delete workflow runs(older than a month)
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6