name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}

jobs:
  sync:
    runs-on: ubuntu-latest
    env: 
      sync_token: ${{ secrets.FORK_SYNC_TOKEN }}
    if: ${{ github.repository_owner != '0xERR0R' && env.sync_token == '' }}
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ env.sync_token }}
          owner: 0xERR0R
          repo: blocky
          base: main
          head: main