name: golangci-lint
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - uses: actions/checkout@v2

      - name: golangci-lint
        run: make lint